[
 {
  "Error": {
   "Message": "ERRORED! Got Exception (if any): ERROR: Bot #0: Received invalid character 'Traceback (most recent call last):T'. (at character 1.)\nInput received from bot:\nTraceback (most recent call last):\n^; Response received (if any): Traceback (most recent call last):  File \"MyBot.py\", line 69, in <module>    navigate_command = attack_ships(ship, entities_by_distance, own_ships, game_map)  File \"MyBot.py\", line 43, in attack_ships    navigate_command = ship.navigate(ship.closest_point_to(nearest_ship, min_distance=0), game_map, speed=int(hlt.constants.MAX_SPEED), entities=own_ships)TypeError: navigate() got an unexpected keyword argument 'entities'",
   "Turn": 1
  },
  "Frames": [
   {
    "Time": 87,
    "Turn": 0
   },
   {
    "Time": 106
   }
  ],
  "PlayerID": 0,
  "PlayerName": "Version2"
 },
 {
  "Error": {
   "Message": "ERRORED! Got Exception (if any): ERROR: Bot #1: Received invalid character 'Traceback (most recent call last):T'. (at character 1.)\nInput received from bot:\nTraceback (most recent call last):\n^; Response received (if any): Traceback (most recent call last):  File \"MyBot.py\", line 69, in <module>    navigate_command = attack_ships(ship, entities_by_distance, own_ships, game_map)  File \"MyBot.py\", line 43, in attack_ships    navigate_command = ship.navigate(ship.closest_point_to(nearest_ship, min_distance=0), game_map, speed=int(hlt.constants.MAX_SPEED), entities=own_ships)TypeError: navigate() got an unexpected keyword argument 'entities'",
   "Turn": 1
  },
  "Frames": [
   {
    "Time": 87,
    "Turn": 0
   },
   {
    "Time": 106
   }
  ],
  "PlayerID": 1,
  "PlayerName": "Version2"
 }
]
